### ISSUE TITLE
Cast to speaker where request comes from

### ISSUE THREAD

**Issue by pjft** [maykar/plex_assistant#129]
Hi

Thanks for putting this together - this is awesome!

One thing I'm finding, having multiple Google Home speakers around the home is that regardless from where I make the request, it'll always cast to the default speaker (if set), unless I explicitly ask for it to be cast in a specific speaker.

Any chance we can default the casting to the speaker where the request came from, similar to using other music providers on Google Home speakers?

Let me know if there's anything I can provide on my end to help with digging into this.

Regards.

**Comment by maykar** [comment]
The "feature" to specify a cast device is a workaround since there is no way to get current device information from IFTTT and if it is possible with DialogFlow I either don't have the skills necessary or it is not yet possible. The main obstacle I ran into with DialogFlow was creating anything more complicated then the current setup that still allowed for a variable webhook address.

**Comment by pjft** [comment]
Of course, makes perfect sense. Thank you so much for putting this together!
