### ISSUE TITLE
play next/unwatched playing the wrong episode

### ISSUE THREAD

**Issue by OppyLock** [maykar/plex_assistant#29]
For example: play the next breaking bad.
The current unwatched order might be season 2 episode 7, but it will play season 2 episode 1.

It's doing that for all shows.  It'll pick the right season, but always go back to episode 1 regardless of whether its unwatched or not.
If I say play season 2 episode 7 of breaking bad then it will play, but still goes back to episode 1 again next time.
No errors in the logs.

**Comment by barisahmet** [comment]
For me, when I say "play next friends on SHIELD", it starts playing S09E01. But next unwatched episode of Friends is S05E13.

I have tried "play unwatched friends on SHIELD" etc. too.

**Comment by demonspork** [comment]
Better yet, get rid of the Unwatched command entirely. 99.9% of the time if someone asks "Play Bob's Burgers" they aren't asking for the first available episode, they are asking for the first unwatched episode of Bob's burgers. Unwatched should be the default and I would prefer it that way because I'm going to be asking for "unwatched" literally every single time.

**Comment by maykar** [comment]
I agree and will be working on this soon

**Comment by maykar** [comment]
Just as an update: I haven't forgotten about this, but with the fixes to pychromecast and a couple of pesky bugs out of the way I wanted to get a release out with that stuff in there.

This is next on the list.

**Comment by maykar** [comment]
This should be remedied in the 0.2.3 release and I have also made it the default action when asking to play a tv show or season.
