### ISSUE TITLE
Moving TV Show Name Disrecpencies

### ISSUE THREAD

**Issue by demonspork** [maykar/plex_assistant#35]
I am frequently encountering mismatches with names. I just tried to "Tell Plex to play Godfather" and it played the movie "Go (1999)" and does so every time I ask the same thing. No logs that I can see. What do I need to do to provide you with logs/help fixing these mismatches?

**Comment by maykar** [comment]
Adding the code below to your configuration.yaml file will add debug logs to your full HA logs. This might help in diagnosing what Google Assistant is hearing and what Plex Assistant is parsing.

```
logger:
  logs:
    custom_components.plex_assistant: debug
```
Plex Assistant uses [fuzzywuzzy](https://github.com/seatgeek/fuzzywuzzy) in order to pick the highest scoring match between the spoken title and a list of media titles. You can help this process in cases where TV shows and movies have the same title by mentioning movie, tv, or show in your command like `"tell plex to play the movie godfather"`. 

In the case you mention though they are very different. Try using complete titles, for example Godfather is actually not the name of the movie, it is "The Godfather". Check the actual movie titles on Plex to see where there may be discrepencies.

**Comment by maykar** [comment]
Looked into this more and this is just an embarassing bug that will be fixed in the next version.

The "the" in "Godfa**THE**r" is getting caught in the detection of the seperator between media and device. Should have a release out soon with the fix as Pychromecast just fixed the grey screen issues. I'm fixing things up since this makes cast delay no longer needed. This will not only speed things up quite a bit, but also make configuration considerably easier. Also tweaking the fuzzy seaching to, hopefully, be more accurate.

**Comment by maykar** [comment]
These issues should be remedied in the latest release
