### ISSUE TITLE
Detected code that attempted to create another Zeroconf instance. 

### ISSUE THREAD

**Issue by diogo-r** [maykar/plex_assistant#71]
Log details (WARING):
Logger: homeassistant.components.zeroconf.usage
Source: components/zeroconf/usage.py:45
Integration: Zero-configuration networking (zeroconf) (documentation, issues)
First occurred: 19:54:48 (1 occurrences)
Last logged: 19:54:48

Detected code that attempted to create another Zeroconf instance. Please use the shared Zeroconf via await homeassistant.components.zeroconf.async_get_instance(hass). Please report this issue.

**Comment by maykar** [comment]
This integration uses the shared Zeroconf instance already. Is this error coming from another integration? Is there more to the error that you didn't share? Are you using an older version of Plex Assistant?

**Comment by diogo-r** [comment]
I am using the latest version. I copied everything in the warning directly from the Home Assistant notifications page.

**Comment by maykar** [comment]
The error doesn't mention Plex Assistant, at least the portion you shared.

**Comment by diogo-r** [comment]
Oh ok, thanks!

**Comment by diogo-r** [comment]
Oh ok, thanks for the quick response!

(Not related to the warning: I did everything that was in the main page but it still doesn't work, is there any chance that we can talk by e-mail or something?)

**Comment by maykar** [comment]
No, but feel free to message me on the [HA forums](https://community.home-assistant.io/u/mayker/) or discord: maykar#7021.

**Comment by diogo-r** [comment]
> No, but feel free to message me on the [HA forums](https://community.home-assistant.io/u/mayker/) or discord: maykar#7021.

How do I discord you without being friends? My discord is diogo_r#9114

**Comment by shoguevara** [comment]
This issue was closed without any further investigations. 
Here are mine:
I've installed Plex Assistant 0.3.1 via HACS 1.9.0 
Configured in the configuration.yaml the following things:

```
plex_assistant:
  url: 'https://my.domain:32400/'
  token: 'my_token'
  default_cast: 'some_chromecast'
  language: 'en'
  tts_errors: true
```

```
sensor:
  - platform: plex_assistant

```  
Here are system logs
```
2020-12-20 16:23:48 WARNING (SyncWorker_5) [homeassistant.components.zeroconf.usage] Detected code that attempted to create another Zeroconf instance. Please use the shared Zeroconf via await homeassistant.components.zeroconf.async_get_instance(hass). Please report this issue.
Stack (most recent call last):
File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
self._bootstrap_inner()
File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
work_item.run()
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/zeroconf/usage.py", line 20, in new_zeroconf_new
_report(
File "/usr/src/homeassistant/homeassistant/components/zeroconf/usage.py", line 45, in _report
_LOGGER.warning(

```

 Sensor successfully shows all chromecast devices I have. But I'm also getting:
 "Detected code that attempted to create another Zeroconf instance."
But as soon as I comment the configuration strings above, the error goes away. 

Please, reconsider reopening this issue azs it clearly needs further work. 
All the error messages are pretty non-descriptive and only thing, that points to the issue caused by plex_assistant, is that the warning goes away on the plex_assistant disabling

**Comment by shoguevara** [comment]
This is a very strange behaviour but I somehow managed to get rid of the warning. And there are only 2 things, that I've changed since:
1. In the Plex Media Server configuration console in the "Network" sectio I specified the "Preferred network interface"
2. Used the Plex Token from WebTools Plugin (yes, it was different from the one I've obtained аfrom XML)

So, that might worth a shot, for those who will also encounter this.

**Comment by maykar** [comment]
The reason this was closed is because I use the method as suggested by HA and the error. If I remove the code to use the HA zerconf instance this is what the error looks like:

```
Detected integration that attempted to create another Zeroconf instance. Please use the shared Zeroconf via await homeassistant.components.zeroconf.async_get_instance(hass).

Please report issue to the custom component author for plex_assistant using this method at custom_components/plex_assistant/__init__.py, line 370
```

Not only does it tell you which component has the issue, it tells you on which line of code it happens on.

Not sure if it helps but a quick search on the forums brought up this thread with the same error:

* [Updating docker fixed it for them.](https://community.home-assistant.io/t/cant-add-google-cast-devices-to-ha-getting-error-when-adding-from-integrations/265089)
